### ISSUE TITLE
Add min/max/size helper functions for reflecting an enum

### ISSUE THREAD

**Issue by rmanaloto-tastytrade** [qlibs/reflect#57]
First of, thanks for this and your other libraries. I am finding them very useful.

Would it be possible to expose the enum_min/enum_max/size functionality embedded inside reflect::enum_name/reflect::detail::enum_cases methods? I am planning to use this library with your mph library to autogenerate lookups of an enum with different string representations and different underlying values (based on different source systems).

So, I'd ideally like to be able to compile-time validate that I have the full list of enum values up front to make sure I didn't miss a value.

**Comment by rmanaloto-tastytrade** [comment]
reviewing your changes now. But I think there is an issue with scoped enums

this seems to fail in your example


```
enum class color : uint8_t { red, green, blue, };

static_assert(3 == std::size(reflect::enumerators<color>));
```

**Comment by rmanaloto-tastytrade** [comment]
I am in the financial trading space (I think you were too). I'm trying to cleanup and consolidate some of our code. 
A lot of the trading/market data/order entry protocols have the same semantics but different data.

For example, a side enum in one exchange/protocol might have an underlying type of char while it might be uint8_t in another. So, I'm trying to normalize this to our internal enum representation. So my use case isn't really with getting the name representation of the enum from my code, but for the immediate getting the min/max/size as mentioned above. I plan to then add meta data about the internal type/string representation of the enums from the other sources and use your mph library to do the lookups/reverse lookups to go from one format/source system to another.

I'm still working out the details. Once I get something concrete I can provide an example. Maybe, you might even find a beter way to do this from your previous experience.

I also need to write serializers to go from one format to another and sometimes a binary format to an ascii format (such as the fix protocol).

**Comment by krzysztof-jusiak** [comment]
Thanks for pointing it out; the issue was interesting and it was related to the enum_max size, which globally was set to 1024 but because of the underlying enum type being uint8_t it should be greater than 255, hence it was reading out of range name data. It's fixed now, I also fixed the string_view and name storage. So the assembly looks better now. - https://godbolt.org/z/Ts5Yh968T (It's basically jump table in this case but due to perfect hashing this solutin scales to any enums with only difference being the precomputed at compile-time mask and data)

```cpp
$enum_name(color):                   # @"$enum_name(color)"
        mov     ecx, edi
        and     ecx, 3
        shl     ecx, 4
        lea     rdx, [rip + mph::v5_0_1::type_traits::constant_t<mph::v5_0_1::find$pext<reflect::v1_2_0::enumerators<color, -1, 128, reflect::v1_2_0::detail::static_vector<unsigned char, 130ul>{std::array<unsigned char, 130ul>{unsigned char [130]{(unsigned char)0, (unsigned char)1, (unsigned char)2}}, 3ul}>>>::value]
        cmp     byte ptr [rcx + rdx], dil
        lea     rax, [rip + .L.str]
        cmove   rax, qword ptr [rcx + rdx + 8]
        ret
$unsafe$enum_name(color):            # @"$unsafe$enum_name(color)"
        and     edi, 3
        shl     edi, 4
        lea     rax, [rip + mph::v5_0_1::type_traits::constant_t<mph::v5_0_1::find$pext<reflect::v1_2_0::enumerators<color, -1, 128, reflect::v1_2_0::detail::static_vector<unsigned char, 130ul>{std::array<unsigned char, 130ul>{unsigned char [130]{(unsigned char)0, (unsigned char)1, (unsigned char)2}}, 3ul}>>>::value]
        mov     rax, qword ptr [rdi + rax + 8]
        ret
.L.str:
        .zero   1

template parameter object for reflect::v1_2_0::fixed_string<char, 3ul>{char [4]{(char)114, (char)101, (char)100}}:
        .asciz  "red"

template parameter object for reflect::v1_2_0::fixed_string<char, 5ul>{char [6]{(char)103, (char)114, (char)101, (char)101, (char)110}}:
        .asciz  "green"

template parameter object for reflect::v1_2_0::fixed_string<char, 4ul>{char [5]{(char)98, (char)108, (char)117, (char)101}}:
        .asciz  "blue"
```

Thank you for you details explanation, very interesting indeed and an interesting approach. Looking forward to seeing how it will go. Regarding reflect::enumerators and min max. Maybe a few things worth pointing out just in case. The values will be sorted in the increasing order and not enum order (simply because how the enum cases deduction works), so min and max will be min=enumerators[0].first, max=enumerators[-1].first. If only enum cases are important it might be worth to transform enum cases pairs to just cases which can be done at compile-time with no overhead. in this case, unless you don't need to store enumerators and/or need names then that wouldn't matter, I think. Depending on the enum REFLECT_ENUM_MIN/REFLECT_ENUM_MAX or reflect::enum_min/reflect::enum_max needs to be considered if the range doesn't fit (the limitations and customization points are purely due to compilation time reasons).

All in all, good luck! Interested to see how it will go and don't hesitate to point out issues/improvements as you already have been doing. Thanks!

**Comment by rmanaloto-tastytrade** [comment]
thanks for quick response and fix

i pulled your latest updates and having a scoped enum of uint8_t looks to be working now.

I'm working through the solution of the task i listed above. I'll post an example once i get it fully working.

And yes, the enum(s) I want to reflect on will be incremented from 0 to N
the underlying value mapping and to_string representations will just be metadata i pass into my enum encoder/decoder/to_string generator
this will allow me to add enums without worrying about sparse values which could affect your reflection parsing
and your mph library will do sorting/perfect hashing for me
