### ISSUE TITLE
type_name produces wrong names using clang on windows

### ISSUE THREAD

**Issue by iAndyHD3** [qlibs/reflect#59]
When using reflect with the clang compiler on windows, `type_name` produces incorrect names. 
This is only the case for built in types, structs and enums seem to work properly.

This is likely because clang mimmics some specific MSVC behaviour on windows, sorry I can't be much more specific (as I'm not skilled enough to understand what's going on in this library)

The only tests that fail are these:
```cpp
static_assert(std::string_view{"int"} == type_name<int>());
static_assert(std::string_view{"int"} == type_name(reflect::test::foo::type{}));
```

If it helps, I ran some small code to output what type_name produces using clang on windows.

```cpp
reflect::type_name<int>():       "void) [Ts = "
reflect::type_name<double>():    "void) [Ts = "
reflect::type_name<float>():     "void) [Ts = "
reflect::type_name<bool>():      "void) [Ts = "
reflect::type_name<bool>():      "void) [Ts = "

reflect::type_name<void>():      "void"
reflect::type_name<foo>():       "foo"
reflect::type_name<E>():         "E"
```

**Comment by krzysztof-jusiak** [comment]
Thanks @iAndyHD3 for reporting. I don't have access to clang-cl compiler, I don't think it's on godbolt, but I think I see the issue. So the library is detecting the type offsets (specific to the compiler) during compilation time by checking if spececific preassigned names (such REFLECT_MY_SUPER_STRUCT) however, unfortunately, there is also void in on case being used instead of REFLECT_MY_SUPER_VOID which has potential to clash with the type name produced by the compiler (in this case likely clang-cl produces void somewhere in the middel of the function name). The solution is to use preassigned REFLECT_MY_SUPER_TYPE instead so that there is no chance for it to be produced by the compipler. I'll make the change and push it, but would it be possible for you to verify it here before official bug fix release? Thanks.

**Comment by iAndyHD3** [comment]
I might not understand what I need to change. What do you mean exactly by using `REFLECT_MY_SUPER_TYPE`? Please be a more descriptive. Sorry for the inconvenience as I'm not familiar with many of these terms.

**Comment by iAndyHD3** [comment]
Yeah, it works correctly now. Thank you!

**Comment by krzysztof-jusiak** [comment]
No need to do any changes on your side, can you please check with the newest HEAD or https://github.com/qlibs/reflect/commit/9bf7c2ff42c031fb939bce2f3f8d5a5fba15a5c5. Thanks.
I think that clang-cl is using void for empty functions like in C - `void foo(void) with Ts = { int }` or something similar, not sure, we shall see :thinking:
